workflows:
  ios-app-store:
    name: VN3 Internet iOS App Store
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic_integration # <--- ADICIONE ESSAS DUAS LINHAS AQUI
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Xcode build and code signing
        script: |
          keychain initialize
          
          # Força a busca e criação automática do certificado e do perfil específicos para App Store
          app-store-connect fetch-signing-files "com.vn3internet.app" --type IOS_APP_STORE --create
          
          keychain add-certificates
          
          # Força o Xcode a entender que a distribuição é oficial de loja (App Store)
          xcode-project use-profiles --export-method app-store
          
          xcode-project build-ipa --project="$XCODE_PROJECT" --scheme="$XCODE_SCHEME"
    artifacts:
      - ios/build/build_output/apps/*.ipa
    publishing:
      app_store_connect:
        auth: integration